name: spotlight_ant
package: spotlight_ant
# bumper-checker: v0.7.0
version: 0.7.0
description: >-
  Spotlight the widget by wrapping it and with highly flexible configuration.
repository: https://github.com/evan361425/flutter-spotlight-ant
environment:
  flutter: ">=3.1.0-0"
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
